version: "3.9"
services:
  ssms:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=P@ssword2
    network_mode: bridge
    ports:
      - 1433:1433
    # volumes:
    #   - "~/docker_volumes/mssql/data:/var/opt/mssql/data"
    # user: root